CFLAGS="-march=x86-64-v3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs"
LTOFLAGS="-flto=auto"
MAKEFLAGS="-j$(nproc)"
NINJAFLAGS="-j$(nproc)"
RUSTFLAGS="-C opt-level=3 -C target-cpu=x86-64-v3"
DEBUG_RUSTFLAGS="-C debuginfo=2"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"
BUILDENV=(!distcc color !ccache check sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto !autodeps)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
MAN_DIRS=(usr{,/local}{,/share}/{man,info})
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc})
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
DBGSRCDIR="/usr/src/debug"
LIB_DIRS=('lib:usr/lib' 'lib32:usr/lib32')
COMPRESSZST=(zstd -c -T0 -9 -)
PKGEXT='.pkg.tar.zst'
PACKAGER="ngoding-id/lumbung <defy-disarray-jury@duck.com>"
GPGKEY="A4468143841CA99F1D776A4246FFD74AD50739CB"
