post_install() {
    echo ""
    echo "jetbrains-toolbox"
    echo "========================================="
    echo "Unofficial package. Don't report issues to upstream!"
    echo "https://github.com/ngoding-id/lumbung/issues"
    echo ""
}

post_upgrade() {
    echo ""
    echo "jetbrains-toolbox"
    echo "========================================="
    echo "Unofficial package. Don't report issues to upstream!"
    echo "https://github.com/ngoding-id/lumbung/issues"
    echo ""
}
